[[app]]
runtime = "PEADAE"
arguments = "--cse --disable-peval cauer_100.dae"
options = "--benchmark-res 11515"

[[app]]
runtime = "PEADAE"
arguments = "--cse --jac-spec-absolute 0 cauer_100.dae"
options = "--benchmark-res 11515"

[[app]]
runtime = "PEADAE"
arguments = "--cse --jac-spec-absolute 1 cauer_100.dae"
options = "--benchmark-res 11515"

[[app]]
runtime = "PEADAE"
arguments = "--cse --jac-spec-absolute 2 cauer_100.dae"
options = "--benchmark-res 11515"

[[app]]
runtime = "PEADAE"
arguments = "--cse --disable-peval cauer_100.dae"
options = "--benchmark-jac 29"

[[app]]
runtime = "PEADAE"
arguments = "--cse --jac-spec-absolute 0 cauer_100.dae"
options = "--benchmark-jac 29"

[[app]]
runtime = "PEADAE"
arguments = "--cse --jac-spec-absolute 1 cauer_100.dae"
options = "--benchmark-jac 29"

[[app]]
runtime = "PEADAE"
arguments = "--cse --jac-spec-absolute 2 cauer_100.dae"
options = "--benchmark-jac 29"

[[post]]
runtime = "id"
